### ISSUE TITLE
信息过滤没有确认或取消选项

### ISSUE THREAD

**Issue by GudelianSolo** [MadYeling/Logs_Chat_Record_Extractor#2]
您好！
我可以正常读取文件但是当想要过滤信息的时候没有可以确定或者取消的选项， .net framework 4.8也是已启用的。可以问一下可能是什么原因导致的吗？谢谢您！

**Comment by MadYeling** [comment]
有时候Windows对窗口的渲染有bug，会导致卡渲染看不到选项，鼠标挪上去能看到按钮，重开软件一般就行。
还有一种可能是因为我没有试过当系统存在缩放的时候UI会变成什么样子，可以尝试在设置-系统-屏幕-缩放里面把缩放调整为100%，然后重启电脑看看。

**Comment by chriscch** [comment]
我也是沒有確定和取消的選項

**Comment by MadYeling** [comment]
用WPF重写了，应该不会再有这个问题出现了
